## Trabajo Práctico: Red Neuronal Lineal.

aca hay que poner una introducción supongo idk

In [1]:
import numpy as np
import sys

from alc import *
# TODO esto todo va a estar en alc cuando terminemos y hay que borrarlo
sys.path.append(".")
sys.path.append("../src")
from labo00_auxiliares import *
from labo01_errores_igualdad import *
from labo02_TLs_basicas import *
from labo03_normas import *
from labo04_LU import *
from labo05_QR import *
from labo06_AVs import *
from labo07_markov import *
from labo08_SVD import *


no se explicar que hacemos las pruebas

In [2]:
import os
os.getcwd()[-3:]


'/TP'

Recordamos, los "t" son los valores de entrenamiento, y los v son los de testeo

In [3]:
Xt, Yt, Xv, Yv = cargarDatasetReducido("cats_and_dogs", 2, 3)
print(Xt, Xt.shape)
print(Xv, Xv.shape)
print(Yt, Yt.shape)
print(Yv, Yv.shape)

[[-0.03650029 -0.12246419  0.58658326]
 [ 0.11822625  0.26049453 -0.02440555]] (2, 3)
[[ 0.01444551  0.14617081  0.35378024]
 [ 0.31209746  0.7037203  -0.01706209]] (2, 3)
[[0 0 0]
 [1 1 1]] (2, 3)
[[0 0 0]
 [1 1 1]] (2, 3)


PinSVD

In [ ]:
def pinvSVD(X, Y):
    """ 
    Obtiene los pesos utilizando la Descomposición
    en Valores Singulares para la resolución de la pseudo-inversa usando el algoritmo 2. 
    U: Matriz de autovectores por izquierda de SVD
    S: Matriz Sigma de valores singulares
    V: Matriz de autovectores por derecha de SVD
    Y: matriz de targets de entrenamiento. 
    retorna pesos W
    """

    U,S,V = svd_completa(X)
    S_ALaMenosUno = np.zeros((len(S),len(S[0])))
    for i in len(S):
        if S[i][i] >0:               # si uno es cero, los que le siguen tambien
            S_ALaMenosUno[i][i] = (S[i][i])**(-1)
    SigmaMas = traspuesta(S_ALaMenosUno[:,len(S)])
    V1 = V[:,len(S)]
    W = matmul(Y, matmul((V1, SigmaMas),traspuesta(U)))

    return W

### QR
voy a intentar que funcione con QR que es la única que creo que ya esta implementada. 

problema: solo funciona sobre matrices cuadradas, hay que cambiar eso
problema: muy lento. vamos a cachearlo una vez calculado en un archivo para no tener que volver a hacerlo

In [4]:

if os.path.isfile("QGS.npy") and os.path.isfile("RGS.npy"):
    Q = np.load("QGS.npy") 
    R = np.load("RGS.npy") 
else:
    Q,R = QR_con_HH(traspuesta(Xt))
    #np.save("QGS.npy",Q)
    #np.save("RGS.npy",R)

In [5]:
print(np.round(Q,3))
print(np.round(R,3))


[[-0.061 -0.412  0.909]
 [-0.204 -0.886 -0.415]
 [ 0.977 -0.211 -0.03 ]]
[[ 0.6   -0.084]
 [-0.    -0.274]
 [ 0.     0.   ]]


In [6]:
W = pinvGramSchmidt(Q,R,Yt)



(3, 2) (3, 3)


IndexError: index 2 is out of bounds for axis 0 with size 2

In [ ]:
Xv

array([[ 0.01444551,  0.14617081,  0.35378024, ...,  0.06960854,
         0.19375077,  0.11677344],
       [ 0.31209746,  0.7037203 , -0.01706209, ...,  0.89421463,
        -0.03304377, -0.09286442],
       [-0.07121716,  0.32912827,  0.07275005, ...,  0.6280458 ,
        -0.05116841,  0.2911249 ],
       ...,
       [ 0.16783825,  0.03959971,  0.03222273, ..., -0.00660932,
         0.18055601,  0.13518912],
       [ 0.1005924 , -0.02867802,  0.32591313, ...,  0.35190883,
        -0.04507048,  0.00601371],
       [ 0.02142541,  0.08016607,  0.28435132, ...,  0.27552518,
         0.14037396,  0.01404417]], shape=(400, 500), dtype=float32)

In [ ]:
YvEsperados = matmul(W, Xv)
print(YvEsperados)


[[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan 